### ISSUE TITLE
Pictures are not refreshing

### ISSUE THREAD

**Issue by valkiii** [camarel/raspifon#17]
Hi, thank you  for the project. I am trying to receive pictures from telegram's bot and I manage to receive it. If in the same session I ask again a picture, the bot/raspberrypi keeps on sending the same one. Pictures only refresh if I restart the script. Any suggestion?

**Comment by thadwald** [comment]
I have the same problem. Did you ever figure this out?

**Comment by valkiii** [comment]
Made my own script.

You can call PiCamera to take a picture like:


    def take_picture():
	
        camera = PiCamera()	
        camera.start_preview()	
        camera.capture('pictures/picture.jpg')	
        camera.stop_preview()	
        camera.close()

This should work. Then you need to send the picture via telegram as:

    def send_picture(update, context):	
        take_picture()	
        update.message.reply_photo(photo=open('pictures/picture.jpg', 'rb'))

**Comment by camarel** [comment]
Hi there, it's a moment I have no been using this. But you are right. The same picture is sent again. I fixed it, hope it works now ;-)
